// Authorship is verified in the document body, not inferred from file metadata.
export const betaDocuments=[
  {id:'beta-tournament',title:'锦标赛与排行榜',name:'锦标赛-排行榜系统文档',author:'吴天昊',signature:'文档撰写人：吴天昊',period:'2020.03—2020.07',value:'活动生命周期、参与路径、阶段奖励、排名结算、休赛展示与未领奖补发。'},
  {id:'beta-story',title:'分支剧情系统',name:'分支剧情系统文档',author:'吴天昊',signature:'文档撰写人：吴天昊',period:'2020.04',value:'角色与章节入口整合、未解锁与待更新状态、重玩菜单和剧情漏斗埋点。'},
  {id:'beta-tasks',title:'限时任务活动',name:'活动-限时任务',author:'吴天昊',signature:'文档撰写人：吴天昊',period:'2020.08',value:'每日与周任务、钥匙进度、阶段领奖、任务跳转返回、换任务与跨期清理。'},
];
export const betaAssets=[
  {file:'tournament-flow.png',width:771,height:760,sha256:'8e7c007e65218021a4fcbff53ef0132a82262b7b6ac97836f146dfd285caecad',source:'《锦标赛-排行榜系统文档》流程示意图',alt:'锦标赛原始流程图：预热与解锁、活动入口、关卡结算、阶段奖励、排名奖励、荣誉兑换和休赛展示'},
  {file:'tournament-entry.png',width:662,height:723,sha256:'593e00406ec70d71e9704655a4e23772c53fd3f2bb92ace7afc1fb67299afd28',source:'《锦标赛-排行榜系统文档》活动开启 UE 图',alt:'锦标赛活动开启界面跳转：主界面入口与活动通知均进入排行榜，面板包括排名、奖励和兑换分页'},
  {file:'story-navigation.png',width:1203,height:515,sha256:'67577c6110f7a89fe0da22ffb51489fe57ecf5d9f2954a026fe384bfd8103a57',source:'《分支剧情系统文档》系统流程图',alt:'分支剧情 UE 流程：主界面到角色故事列表，展开单个角色章节，再进入剧情或重玩菜单'},
  {file:'task-interaction.png',width:1103,height:629,sha256:'0e251a9783fe162748bc170911aa95ffbb84dbd95c295e11d720487009c997cf',source:'《活动-限时任务》流程与界面参考',alt:'限时任务 UE 图：每日与周任务、阶段奖励进度、主线与剧情跳转、购买钥匙和更换任务确认弹窗'},
  {file:'event-ranking-reference.png',width:394,height:655,sha256:'bb71798a12b2f99bc4308abafe7836b49a5a716d31929b47723fafff4147f3b9',source:'《2020-03活动美术需求》第 1 页内嵌排行面板参考',alt:'活动美术需求内的已有排行榜界面参考：标题、角色和奖励展示、倒计时及下方排行内容区域'},
  {file:'event-collection-reference.png',width:474,height:733,sha256:'2a80e9de0a25470e4d5278a519db203220ce0d6b18b259de8ab165576dd883ed',source:'《2020-03活动美术需求》第 4 页内嵌兑换面板参考',alt:'活动美术需求内的已有收集兑换界面参考：顶部主题展示与倒计时，下方部件网格、获得状态及兑换消耗'},
];
const imagePath=(base,file)=>`${base}assets/project-design/word-villas/${file}`;
function image(file,e,base){const item=betaAssets.find(a=>a.file===file);return `<img src="${imagePath(base,file)}" width="${item.width}" height="${item.height}" loading="lazy" decoding="async" alt="${e(item.alt)}">`;}
function evidence({id,title,file,question,points,output},e,base){const item=betaAssets.find(a=>a.file===file),path=imagePath(base,file);return `<article class="matchmaking-map" id="${id}" aria-labelledby="${id}-title"><h3 id="${id}-title">${e(title)}</h3><figure><a href="${path}" aria-label="查看${e(title)}原图">${image(file,e,base)}</a><figcaption>${e(item.source)} · 原始嵌入图</figcaption></figure><div class="matchmaking-map-notes"><div><h4>设计问题</h4><p>${e(question)}</p><h4>文档产出</h4><p>${e(output)}</p></div><div><h4>关键方案</h4><ul>${points.map(p=>`<li>${e(p)}</li>`).join('')}</ul></div></div><a class="design-original" href="${path}">查看原图（可缩放）<span aria-hidden="true">↗</span></a><details class="matchmaking-inspect"><summary>在页面内阅读${e(title)}大图</summary><div class="matchmaking-scroll" tabindex="0" role="region" aria-label="${e(title)}大图阅读区域">${image(file,e,base)}</div></details></article>`;}
export function renderBetaDesign(e,base='../../'){
  return `<section class="matchmaking-design" id="beta-design" aria-labelledby="beta-design-title"><header><p class="eyebrow">AUTHORED DESIGN / 贝塔科技 · Word Villas</p><h2 id="beta-design-title">署名策划与交互设计</h2><p class="matchmaking-intro">以三份正文明确署名的策划案，展开竞技活动、角色剧情与任务目标的设计。我的任职角色：高级系统策划，2020.03—2021.02。</p></header><p class="matchmaking-boundary">三份文档均明确写有“文档撰写人：吴天昊”。本人确认相关功能已从设计推进到上线；下方保留历史规则与迭代，不代表每个方案细节均为最终版本。美术执行属于团队相关岗位，设计目标与示例排名、奖励、价格均不是实际业绩。</p><nav class="idiom-jumps" aria-label="贝塔设计资料">${betaDocuments.map(d=>`<a href="#${d.id}">${e(d.title)} ↓</a>`).join('')}<a href="#beta-art">活动美术需求 ↓</a><a href="${base}projects/word-villas/design-summary/">设计摘要 ↗</a></nav>
    <section class="idiom-chapter" aria-labelledby="beta-documents-title"><h3 id="beta-documents-title">重点署名策划案</h3><div class="beta-document-list">${betaDocuments.map(d=>`<div><h4><a href="#${d.id}">${e(d.name)}</a></h4><p>${e(d.value)}</p><p class="matchmaking-boundary">${e(d.signature)} · 修订记录 ${e(d.period)}</p></div>`).join('')}</div><p class="matchmaking-boundary">资料按 Word Villas 的任务标题、角色与场景参考接入该项目，不将同公司其他项目自动视为这些文档的成果。完整内部文档、剧本、埋点数据、奖励表与经济配置不公开。</p></section>
    ${evidence({id:'beta-tournament',title:'锦标赛的生命周期与奖励闭环',file:'tournament-flow.png',question:'如何让主线进度不同的玩家参与独立竞技，并让活动结束后的奖励和展示仍然可用？',points:['以独立挑战关替代只依赖主线连击的排行路径，解决已经完成主线的老玩家缺少竞争入口的问题。','将预热、解锁、活动开启、关卡结算、阶段奖励、赛季结算和休赛期串联起来；排名奖励与荣誉兑换分别承接短期和长期目标。','休赛期继续查看奖励和兑换；前三名可上传独立装扮展示，与主界面和剧情换装记录区分。','记录未领奖玩家，跨入新赛季时通过邮件补发；参与、阶段领奖、排名领奖和兑换各自定义埋点。'],output:'正文含多轮修订记录，覆盖规则、关卡、奖励、门票与埋点。门票规则曾随版本调整，图中旧阈值和示例不作为当前线上配置；这里只公开流程与交互关系。'},e,base)}
    ${evidence({id:'beta-tournament-ui',title:'从活动通知到排行面板',file:'tournament-entry.png',question:'预热通知、主界面小入口与活动主面板，如何把玩家带到同一参与路径？',points:['主界面入口与通知中的 GO 按钮都进入锦标赛展示面板，避免两个入口产生不同参与流程。','面板分为排名、奖励与兑换三类信息；排名强调前三名及玩家附近名次，保留滚动查看。','帮助提示、倒计时、查看奖励与进入关卡分别承担规则说明、时间感知和行动入口。'],output:'活动开启 UE 图将解锁条件、通知弹窗与展示面板连接，可用于策划、程序和 UI 对齐页面跳转；示例头像与名次不是真实用户排行数据。'},e,base)}
    ${evidence({id:'beta-story',title:'角色剧情入口、锁定与重玩',file:'story-navigation.png',question:'怎样把分散的角色故事集中展示，并区分可游玩、尚未解锁与等待更新？',points:['角色列表统一收纳故事，展开后展示简介、当前章节和可用章节数，再由 PLAY 进入剧情。','尚未解锁时按钮置灰并展示解锁条件；已有内容完成但未更新时显示等待更新，不误导玩家重复点击。','重玩菜单区分当前故事、回到第一章及取消；新章节在主入口和角色条目上提示。','分别记录故事开始、两种重玩、分支选择及付费选择，为开始与中断漏斗提供事件定义。'],output:'署名文档的修订记录明确提到 UE 流程与界面调整、入口整合和重玩逻辑；图中的角色美术为团队界面参考，不表示本人绘制或独立撰写全部剧本。'},e,base)}
    ${evidence({id:'beta-tasks',title:'任务目标、阶段领奖与跳转返回',file:'task-interaction.png',question:'如何让每日和周任务共同推进活动目标，并让操作后的状态与返回路径清晰？',points:['完成任务获得钥匙，钥匙累计进度激活阶段奖励；任务区与奖励区分别支持纵向和横向浏览。','每日任务优先、周任务随后，已完成任务置灰并后排；区分未完成、完成待领取、已领取三种按钮状态。','GO 跳转到主线或分支剧情，从目标界面返回主界面时重新打开活动面板，延续任务上下文。','未完成任务可确认后更换，只在相同日/周类型中抽取未完成过的任务；钥匙跨期清零，消费与奖励数值不在此公开。'],output:'文档将任务库、排序、奖励状态、跳转恢复、换任务弹板、资源条与埋点需求一起交付；UI 参考与最终配置在正文中明确区分。'},e,base)}
    <section class="idiom-chapter" id="beta-art" aria-labelledby="beta-art-title"><p class="eyebrow">ART BRIEF / 界面资源参考</p><h3 id="beta-art-title">从活动规则到美术需求</h3><p>《2020-03活动美术需求》按活动列出标题、角色、背景、UI 主题与配套入口图。下面两张是需求文件内的已有界面参考，不是对应新主题的最终成品，也不认定该美术需求文件由本人独立撰写。</p><div class="idiom-assets-grid">${betaAssets.slice(4).map(item=>`<figure class="idiom-reference"><a href="${imagePath(base,item.file)}" aria-label="查看${e(item.alt)}原图">${image(item.file,e,base)}</a><figcaption><span>${e(item.source)}</span><a href="${imagePath(base,item.file)}">查看原图 ↗</a></figcaption></figure>`).join('')}</div><div class="matchmaking-map-notes"><div><h4>交付拆分</h4><p>排行活动需要标题、倒计时、角色与奖励展示和排行内容区；收集兑换需要部件列表、未获得状态与消耗入口。需求同时覆盖入口小图和活动通知，减少只交付主面板而遗漏入口的情况。</p></div><div><h4>职责边界</h4><p>署名策划案用于说明我的规则和交互文档贡献；这些图用于说明团队美术配合与需求表达。已有参考的题材不等于新活动最终上线题材，不使用未经核实的第三方主题素材作个人成果。</p></div></div></section></section>`;
}
