export const bolangAssets=[
  {project:'matchmaking-inc',file:'skill-tree.png',width:1280,height:720,sha256:'77cf17bb027fd16dfb6a0f60802e8a3a6b405e40abe28ac325e9b369073946e2',source:'《【核心系统】技能系统》第 7 页，界面效果与资源标注',alt:'技能树历史效果图：阶段分层、技能连线、未解锁灰态、选中描边和右侧激活信息'},
  {project:'matchmaking-inc',file:'decor-editor.png',width:1280,height:722,sha256:'3d0e80e246482e069ad02c06836d8708f3d33082fe3aea09848da165156cae8b',source:'《【模拟经营】装修系统》第 7 页，家具编辑界面',alt:'会所装修历史界面：场景预览、家具分类、使用中勾选、价格、已购、未解锁和购买按钮'},
  {project:'matchmaking-inc',file:'emotion-panel.png',width:1280,height:720,sha256:'cd4de1b9b33fc391c23323cbdbe25fc298795c6708cc715c96e204efb5a635bb',source:'《【核心系统】情感系统》第 2 页，情感界面参考',alt:'情感界面历史参考：角色切换、朋友到挚友的阶段进度、阶段条件、已完成勾选、喜好信息和约会换装入口'},
  {project:'matchmaking-inc',file:'show-skills.png',width:1280,height:720,sha256:'b3c0c682b1984c24b00fb1173481aa6b6e972fa261898d2fe8a9f10769f80889',source:'《【补充系统】相亲节目（非诚勿扰）》第 6 页，技能使用效果图',alt:'相亲节目技能效果草图：舞台留灯状态、收视热度、限时施展提示、跳过按钮以及可用和不可用技能'},
  {project:'vanity-fair',file:'feature-map.png',width:1600,height:2348,sha256:'922169f22b312b063a136b6dbbf9e68a7ae2d57ea22596bf28c1ab3a328672e8',source:'《名利游戏》策划案，三、思维导图',alt:'名利游戏功能导图：视频播放、条件选项、分支线路、界面、音效和进阶交互；部分人物关系和手机功能标注待定'},
  {project:'vanity-fair',file:'play-flow.png',width:768,height:1515,sha256:'451d93936572307a3d902385f9d6609fdafa234ddd4dc24f9e4777460b35beab',source:'《名利游戏》策划案，四、操作流程；附件二亦有同图',alt:'名利游戏操作流程：根据存档开始或继续视频，循环片段展示选项，分支推进或进入结局，可从故事线返回探索'},
  {project:'vanity-fair',file:'menu-art.png',width:1920,height:1080,sha256:'3cc74d21bd258bb0f30e75adb7d8827d2fe4e84f8a87befb6a2306cffc583172',source:'名利游戏项目 Resources/UI/Menu/menu_bg.png，团队主菜单底图',alt:'名利游戏团队主菜单底图：剧院舞台与作品中文英文标识，不包含完整菜单按钮'},
  {project:'vanity-fair',file:'storyline-guide.png',width:1920,height:1080,sha256:'639fc6a4cc2efe642cb56004d22b3daf6cd41729b30f7c600951a16b7f198973',source:'名利游戏项目 Resources/UI/Choose/choose_help_bg.png，团队故事线帮助贴图',alt:'故事线帮助原始贴图：矩形节点、分支连线、点亮与灰态菱形、锁定符号和层级箭头，不含剧情剧透'},
];
const asset=(file)=>bolangAssets.find(a=>a.file===file);
const path=(a,base)=>`${base}assets/project-design/${a.project}/${a.file}`;
function image(a,e,base){return `<img src="${path(a,base)}" width="${a.width}" height="${a.height}" alt="${e(a.alt)}" loading="lazy" decoding="async">`;}
function article(c,e,base){const a=asset(c.file);return `<article class="matchmaking-map" id="${c.id}" aria-labelledby="${c.id}-title"><h3 id="${c.id}-title">${e(c.title)}</h3><figure><a href="${path(a,base)}" aria-label="查看${e(c.title)}原图">${image(a,e,base)}</a><figcaption>${e(a.source)} · 原始资料</figcaption></figure><div class="matchmaking-map-notes"><div><h4>设计问题</h4><p>${e(c.question)}</p><h4>文档产出与来源</h4><p>${e(c.output)}</p></div><div><h4>关键方案</h4><ul>${c.points.map(p=>`<li>${e(p)}</li>`).join('')}</ul></div></div><a class="design-original" href="${path(a,base)}">查看原图（可缩放）<span aria-hidden="true">↗</span></a><details class="matchmaking-inspect"><summary>在页面内阅读${e(c.title)}大图</summary><div class="matchmaking-scroll" tabindex="0" role="region" aria-label="${e(c.title)}大图阅读区域">${image(a,e,base)}</div></details></article>`;}
const matchCases=[
  {id:'match-skills',title:'技能树的成长目标与状态反馈',file:'skill-tree.png',question:'如何将日常行为获得的经验转化为长期目标，并让玩家理解当前为何不能学习技能？',output:'《技能系统》更新表记录修改人吴天昊，包含创建文档、技能树重构、解锁逻辑与效果图细化（2023.01—11）。原图中的资源名是历史交付标注，不公开完整配置。',points:['以前置技能、阶段解锁和经验消耗组织成长，将小游戏、任务与邀请入会连接到角色能力。','区分未解锁、已解锁未激活、已激活及满级状态；锁定技能仍可选中查看详情，帮助规划后续目标。','激活与升级按钮说明不足原因；满级后隐藏消耗与升级按钮，阶段进度显示距离下一层的要求。','切回页签保留上次选择；新解锁技能用红点提示，查看后清除，避免提示长期堆积。']},
  {id:'match-decor',title:'会所装修的预览、购买与应用',file:'decor-editor.png',question:'怎样让经营投入既改变场景，也形成明确的功能解锁和收集目标？',output:'《装修系统》由其他成员创建；本人在 2023.07—10 的更新表中记录了细节、界面交互、空间页签、评分与购买后自动应用修订。本站不将初始方案或团队美术归为个人独立成果。',points:['区分数值向与功能向家具，建立会所氛围、声望与系统开放之间的关系。','进入编辑模式保留类别和当前使用家具；选中时高亮场景位置并调整镜头，退出后恢复人物与镜头。','家具列表区分未解锁、可购买、已购和使用中，详情说明解锁条件；购买成功自动应用，减少重复操作。','以阶段性氛围评选补充弱经营目标；提示、页签红点和购买按钮分别表达发现、条件与操作状态。']},
  {id:'match-emotion',title:'情感阶段与条件化交互',file:'emotion-panel.png',question:'怎样把好感数值、支线条件和约会操作组成一条可理解的关系成长线？',output:'《情感系统》初始创建与阶段奖励含其他成员贡献；更新表记录本人补充好感度与界面逻辑、重构为情感系统（2023.06、11）。界面参考与团队角色美术分开归属。',points:['用相逢、熟人、朋友、挚友、恋人组织阶段目标；好感达到上限仍需满足阶段条件，溢出进度在解锁后承接。','角色切换同时刷新阶段、条件、喜好和角色表现；达成条件用勾选等反馈，不只显示一个进度数字。','约会入口随阶段和进行中状态变化；邀约冷却与爽约冷却通过演出说明，不将不可操作原因隐藏。','喜好信息按直接显示、谜题及条件解锁分层呈现；任务、送礼、换装和关系培养由同一阶段逻辑连接。']},
  {id:'match-show',title:'相亲节目的技能时机与现场反馈',file:'show-skills.png',question:'如何让玩家从观察匹配变成主动主持，并把现场判断转为明确的操作时机？',output:'《相亲节目（非诚勿扰）》更新表记录修改人吴天昊，包含创建、界面流程、技能设定和细化（2025.03）。这是后续七阶段版本；下方原有五阶段简历修改方案是早期版本，两者不能混作同一套规则。',points:['开场查看嘉宾简历并选择携带技能，进入节目后以话题、留灯与热度表达局势变化。','技能区分可用、当前场景可释放及冷却或次数耗尽，快捷键与悬停说明配合状态表现。','释放窗口提供倒计时及跳过入口，过时按跳过处理；准备页在次数耗尽时置灰开播并解释原因。','将牵手结果与节目热度分别纳入结算设计；这里不公开技能参数、奖励数值或剧本，也不将热度当实际收视数据。']},
];
export function renderMatchmakingSupplement(e,base='../../'){
  return `<section class="matchmaking-design" id="matchmaking-supplement" aria-labelledby="matchmaking-supplement-title"><header><p class="eyebrow">SYSTEM / GAMEPLAY / UI·UE</p><h2 id="matchmaking-supplement-title">从系统规则到玩家操作</h2><p class="matchmaking-intro">在已有系统总图与资源循环之外，用技能成长、会所装修、情感阶段和节目玩法说明设计如何落到操作与反馈。</p></header><p class="matchmaking-boundary">贡献依据为文档更新表中的修改人和修订内容，不凭目录归属认定独立作者。团队美术用于说明界面表现；历史方案与示例数值不代表所有功能上线或实际业绩。</p><nav class="idiom-jumps" aria-label="相亲补充资料">${matchCases.map(c=>`<a href="#${c.id}">${e(c.title)} ↓</a>`).join('')}<a href="${base}projects/matchmaking-inc/design-summary/">设计摘要 ↗</a></nav>${matchCases.map(c=>article(c,e,base)).join('')}</section>`;
}
const vanityCases=[
  {id:'vanity-modules',title:'视频、选择与故事线的模块拆分',file:'feature-map.png',question:'如何把真人视频内容组织为可配置、可探索的互动叙事产品？',output:'《名利游戏》策划案的功能导图，配合《附件二》《玩法功能需求清单》阅读。三份文档未署名，只用来说明项目需求范围；本人角色沿用已确认的主策划 / 执行制作人经历。',points:['将视频播放、选项逻辑、分支线路、界面及音效分为模块，区分内容承载、选择判断与探索反馈。','条件选项可锁定或隐藏；选择可触发片段跳转、关系变化或特定分支，点击后退出循环视频并隐藏选项。','故事线节点区分已解锁与未解锁，连线表达已走过路径；支持拖动、回到当前节点与已解锁片段跳转。','探索进度与结局进度分别定义；导图和正文中的待定功能、限时选项与扩展设想不作为最终上线承诺。']},
  {id:'vanity-flow',title:'从存档续播到分支回看的操作闭环',file:'play-flow.png',question:'怎样让开始、继续、选择与失败回看形成连续体验，而不是孤立播放片段？',output:'策划案与附件二中的原始操作流程图，不包含具体剧本、视频编号、选择答案或结局剧透。资料说明历史需求，不将存档、引擎与平台接入归为本人程序实现。',points:['按有无存档提供开始或继续入口，继续时回到记录片段，故事线入口提供章节与路径浏览。','循环片段承载选择等待，选定后进入对应视频；首次片段不提供跳过，已看内容的控制与未看内容区分。','失败结局后可回到故事线重新探索，节点解锁与路径点亮帮助玩家判断已看和未看内容。','章节完成与最终视频分别判断；播放结束后进入对应结局或返回主入口，进度和成就需求单独对齐。']},
  {id:'vanity-storyline',title:'故事线的视觉编码与回看提示',file:'storyline-guide.png',question:'如何在复杂分支中让玩家识别节点、锁定路径和下一层，而不提前泄露剧情？',output:'项目自身 UI/Choose/choose_help_bg.png 原始帮助贴图，未补画剧情缩略图或伪造运行界面。此贴图不是完整界面，实际节点、文字和操作由 UI 其他元素组合。',points:['矩形承载片段节点，分支连线说明路线关系，菱形和锁符号分别提供进度与条件提示。','亮色与灰态表达不同状态，层级箭头帮助理解路径继续方向；正文摘要补充状态含义，避免只靠颜色读图。','可拖动的大图与定位入口服务重复探索，帮助图负责解释视觉规则，不承担所有剧情信息。','界面与图标属于团队美术资源，展示的是策划需求与交互表达之间的关系，不声称本人绘制。']},
];
export function renderVanityDesign(e,base='../../'){
  const cover=asset('menu-art.png');
  return `<section class="matchmaking-design" id="vanity-design" aria-labelledby="vanity-design-title"><header><p class="eyebrow">INTERACTIVE NARRATIVE / UI·UE</p><h2 id="vanity-design-title">名利游戏：选择与故事线</h2><p class="matchmaking-intro">以主策划 / 执行制作人角色参与的真人互动叙事项目。以下资料展示功能拆分、操作闭环与故事线交互表达。</p></header><p class="matchmaking-boundary">项目文档未署名，不据此认定本人独立撰写全部方案、剧本或程序。原始图和贴图来自用户指定项目目录，美术执行属于团队；历史需求与待定事项不作为最终上线范围或量化业绩证明。排除文档中的其他游戏临时参考图，不上传原视频、完整剧本和配置。</p><figure class="project-reference-image"><a href="${path(cover,base)}" aria-label="查看名利游戏主菜单原始底图">${image(cover,e,base)}</a><figcaption><span>${e(cover.source)} · 非完整运行界面</span><a href="${path(cover,base)}">查看原图 ↗</a></figcaption></figure><nav class="idiom-jumps" aria-label="名利游戏设计资料">${vanityCases.map(c=>`<a href="#${c.id}">${e(c.title)} ↓</a>`).join('')}<a href="${base}projects/vanity-fair/design-summary/">设计摘要 ↗</a></nav>${vanityCases.map(c=>article(c,e,base)).join('')}</section>`;
}
