export const gooseAssets=[
  {file:'system-map.png',width:1131,height:734,sha256:'953aadfa59428e82b7a8cb86d8d0f1f5d9f0a1e90022a98ba2bc94af34c9686e',source:'《超级铲屎官》立项策划案 5.2 系统结构图',alt:'主界面连接成长、资源收取、好友、图鉴、成就和商店的系统结构图'},
  {file:'economy-cycle.png',width:1179,height:717,sha256:'1f5d120ce0d19ba11b5cbe35b9aaf3a5b8ea2652cc10a7a072335e7905e2d805',source:'《超级铲屎官》立项策划案 5.3 经济系统循环图',alt:'资源生产、培养升级、社交收取与容量扩展之间的经济循环图'},
  {file:'social-flow.jpeg',width:960,height:912,sha256:'9564d910e6e488dd8774bf264bcce000d6ecadf6b910309eb0f16921be421fb6',source:'《超级铲屎官》立项策划案 6.3 社交玩法系统设计流程图',alt:'好友邀请、派遣选择、等待产出、收取与小游戏成功失败的操作流程'},
  {file:'home-proposal.png',width:359,height:640,sha256:'04258942e860f5dd2285fcf25020f3b205f5fc3aad18a9be873cb85c2a5f7f9f',source:'《超级铲屎官》立项策划案 6.1 主界面设计',alt:'历史主界面方案：上方资源、中部经营场地、下方常用入口与侧边功能菜单'},
];
export const gooseCases=[
  {id:'goose-systems',title:'从经营目标拆解系统结构',file:'system-map.png',question:'如何让放置产出、成长目标与社交玩法形成关联，而不是堆叠功能入口？',output:'立项案第 5.2 节将主界面与资源、培养、社交、收集和商业化入口连接，详细系统文档继续说明规则及跳转。',points:['以主场景为中心组织系统层级，区分常用入口与扩展功能。','将图鉴、成就与成长连接，为持续培养提供阶段目标。','区分世界榜、好友榜、好友申请与拜访，细化社交模块的职责边界。']},
  {id:'goose-economy',title:'把产出与成长投入连接成循环',file:'economy-cycle.png',question:'怎样让放置收益有持续的投入方向，并让容量与培养形成不同的成长目标？',output:'第 5.3 节经济循环图整理生产、收取、培养、购入与升级的关系，展示系统与资源设计的结构表达。',points:['通过培养与产出构成基本循环，再以社交收取扩展资源获取路径。','区分生产能力、场地容量与存储上限，使成长投入具有不同作用。','连接图鉴和成就的阶段奖励；原图中的资源关系为历史方案，不公开价格、概率或完整配置，也不作为经营效果证明。']},
  {id:'goose-social',title:'将社交规则落到操作与反馈',file:'social-flow.jpeg',question:'邀请与派遣涉及多名玩家，如何说明可操作条件、等待状态和结果反馈？',output:'第 6.3 节同时提供规则正文与操作流程图，覆盖邀请、仓库选择、派遣、等待和收取；原图含历史示例界面。',points:['区分主动拜访与收到邀请后的跳转；已占用位置不能再次派遣。','用进度与可收取状态衔接等待和行动，并定义撤回、结束及消息反馈。','收取与小游戏分开判断，成功和失败提供不同结果；图中样例数值不是实际经营数据或当前配置。']},
  {id:'goose-interface',title:'让高频入口服务核心体验',file:'home-proposal.png',question:'如何减少访问核心功能的操作，同时为后续功能保留扩展空间？',output:'更新说明明确将常用入口从折叠菜单移至主界面下方，调整收取容器的位置并缩小加速按钮；主界面图提供交付参考。',points:['围绕资源、经营场地和常用入口组织信息层级，让核心行为更容易发现。','背包区分在场与库存，处理成长暂停、满级和交换条件；按钮随状态改变。','成就区分未完成、可领取与已领取，并说明排序、红点和刷新时机。图为需求方案，团队美术资源不认定为本人独立绘制。']},
];
export function renderGooseDesign(e,base='../../'){
  const image=(a)=>`<img src="${base}assets/project-design/versatile-dog/${a.file}" width="${a.width}" height="${a.height}" loading="lazy" decoding="async" alt="${e(a.alt)}">`;
  return `<section class="matchmaking-design" id="goose-design" aria-labelledby="goose-design-title"><header><p class="eyebrow">SYSTEM DESIGN / ECONOMY / UI·UE</p><h2 id="goose-design-title">养成经营：系统、循环与交互</h2><p class="matchmaking-intro">从系统关系到资源循环，再到界面状态与操作流程，展示策划方案如何落到可讨论的交付内容。</p></header><p class="matchmaking-boundary">按用户最新确认，Goose 资料对应《百变汪星人》，不再归入《谁是火车王》。立项原文标题为《超级铲屎官》，正文称其基于《疯狂鹅场》后续开发；保留历史名称，不把方案标题直接认作最终上线名称。立项案页眉署名“策划：吴天昊”；封面另有笔名，未据此推定身份。图中美术由团队承担，历史方案不代表全部已上线。</p><nav class="idiom-jumps" aria-label="养成设计资料">${gooseCases.map(c=>`<a href="#${c.id}">${e(c.title)} ↓</a>`).join('')}<a href="${base}projects/versatile-dog/design-summary/">设计摘要 ↗</a></nav>${gooseCases.map(c=>{const a=gooseAssets.find(a=>a.file===c.file),url=`${base}assets/project-design/versatile-dog/${a.file}`;return `<article class="matchmaking-map" id="${c.id}" aria-labelledby="${c.id}-title"><h3 id="${c.id}-title">${e(c.title)}</h3><figure><a href="${url}" aria-label="查看${e(c.title)}原图">${image(a)}</a><figcaption>${e(a.source)} · 文档提取原图 · 历史需求</figcaption></figure><div class="matchmaking-map-notes"><div><h4>设计问题</h4><p>${e(c.question)}</p><h4>文档产出与来源</h4><p>${e(c.output)}</p></div><div><h4>关键方案与工作价值</h4><ul>${c.points.map(p=>`<li>${e(p)}</li>`).join('')}</ul></div></div><a class="design-original" href="${url}">查看原图（可缩放） ↗</a><details class="matchmaking-inspect"><summary>在页面内阅读${e(c.title)}大图</summary><div class="matchmaking-scroll" tabindex="0" role="region" aria-label="${e(c.title)}大图阅读区域">${image(a)}</div></details></article>`;}).join('')}<p class="design-source">来源：Goose 目录中的《超级铲屎官》立项策划案_20180629.doc，封面日期为 2018/6/14，文件名为 20180629 版本；另核对主界面、背包、好友和成就功能文档。立项案的在场／库存分页与单独背包文档的狗窝结构不完全一致，按不同版本阅读，不断言最终采用哪版；好友文档未署名，不扩为个人独立作者。完整原件、提审登记、市场测试数据、配置与程序文件未公开。</p></section>`;
}
