import {renderMatchmakingDesign} from './matchmaking-design.mjs';
export const materialCases = [
 {project:'matchmaking-inc',company:'bolang',title:'相亲玩法',source:'《补充系统：非诚勿扰相亲》署名玩法方案，2025年3月更新记录',background:'会所经营中的相亲环节需要让玩家参与判断，而不只等待自动配对。',role:'署名更新记录确认我负责该玩法方案与效果图说明；界面美术由团队相应岗位承担。',scheme:'将流程拆为简历调整、舞台登场、话题交流、反选与结算，分别描述玩家选择和系统反馈。',output:'形成五阶段玩法规则与界面说明，用于团队对齐实现。材料证明方案产出，不证明所有功能上线或经营效果。',steps:['调整简历 · 准备匹配条件','登场与话题 · 提供策略选择','反选 · 处理互动反馈','结算 · 收束本轮流程'],boundary:'流程图由本站依据脱敏摘要重新绘制；另附用户授权的两张系统设计截图；完整 PDF 未公开。'},
 {project:'party-planet',company:'quwan',title:'关卡与任务系统',source:'《关卡玩法优化方案》《主线任务》署名更新记录，2022年',background:'关卡、转盘、目标提示和任务系统需要形成连贯的游玩路径。',role:'两份文档的创建与修改记录署名吴天昊，确认关卡交互优化与主线任务方案工作。',scheme:'整理按钮按下与长按自动反馈、倍率解锁提示、地图布局和新手路径；主线任务区分行为与收集判定，明确跳转、红点与领奖状态。',output:'形成版本化优化需求、主线任务规则与状态反馈说明。文档中的留存和参与率是目标，不作为已达成业绩。',steps:['看到目标 · 任务与关卡入口','执行操作 · 按钮与长按反馈','判断进度 · 行为和收集规则','完成领奖 · 状态与下一步'],boundary:'本站原创交互结构图；不展示内部配置、概率、奖励数值和数据目标。'},
 {project:'crisis-dawn',company:'hero-games',title:'PC界面与操作',source:'本人已确认履历；项目界面交互资料仅作背景核对',background:'PC移植需要重新梳理界面层级、HUD操作提示与系统交互。',role:'沿用已确认的PC移植、UI/UE、HUD操作和家园公会调优职责；未署名文档不单独归为我的独立方案。',scheme:'围绕界面遮挡、可用状态表达和引导文案整理体验问题，推进跨岗位调整。本文仅说明已确认的职责范围，不将具体发电机或按键自定义方案归为个人设计。',output:'可证实职责范围为PC体验与协作推进；现有资料补充了项目问题背景，没有新增个人独立实现或量化效果主张。',steps:['识别问题 · 层级与可用状态','梳理操作 · HUD和提示路径','跨岗对齐 · 界面与系统协作','核对反馈 · 回到实际体验'],boundary:'本站依据已确认职责绘制；PC任务原图与同事署名需求未公开。'},
 {project:'vanity-fair',company:'bolang',title:'互动叙事设计',source:'本人已确认履历；《名利游戏》策划案及功能需求材料作项目背景',background:'真人视频叙事需要通过选择、分支与进度反馈形成可操作的体验。',role:'以主策划／执行制作人身份参与项目；文档未署名，不将引擎、SDK、美术和全部剧情归为个人执行。',scheme:'围绕视频播放、条件选择、故事线节点与章节进度组织需求，推动互动叙事规则和交付范围对齐。',output:'项目材料可证实上述需求范围；本摘要说明参与角色与需求背景，不据此声称独立完成所有功能或逐项确认最终上线范围。',steps:['播放片段 · 承载叙事','呈现选择 · 说明条件和反馈','进入分支 · 连接故事节点','记录进度 · 回看章节路径'],boundary:'本站原创需求结构图，不展示剧情剧透、原视频或文档中的第三方临时参考图。'},
];
export function renderMaterialCases(cases,e,base='../../',notes=false){return `<section class="project-design" id="materials" aria-labelledby="materials-title"><div class="section-head"><div><p class="eyebrow">DESIGN JOURNAL / 方案摘要</p><h2 id="materials-title">项目方案<span class="title-dot">.</span></h2></div><p>读背景、职责、方案与可证实产出。</p></div><div class="design-references">${cases.map(c=>{const image=`${base}assets/diagrams/material-${c.project}.svg`;return `${renderMatchmakingDesignFor(c,e,base)+renderProjectReference(c,base)}<article class="design-reference"><figure class="design-overview"><a href="${image}" aria-label="放大${e(c.title)}原创流程图"><img src="${image}" width="760" height="620" loading="lazy" alt="${e(c.steps.join('；'))}"></a><figcaption>${e(c.title)} · 本站原创脱敏结构图</figcaption></figure><div class="design-copy"><span class="panel-label">PROJECT / 工作说明</span><h3>${e(c.title)}</h3>${[['项目背景',c.background],['本人职责',c.role],['关键方案',c.scheme],['可证实产出',c.output]].map(([t,p])=>`<h4>${t}</h4><p>${e(p)}</p>`).join('')}<p class="design-source">摘要依据：${e(c.source)}。${e(c.boundary)}</p><a class="design-original" href="${image}">放大流程图 ↗</a>${!notes?`<a class="text-link" href="${base}projects/${c.project}/design-summary/">阅读文档摘要 ↗</a>`:''}</div><details class="design-inspect"><summary>在页面内阅读流程图<span aria-hidden="true">＋</span></summary><p>可滚动阅读大图；也可打开流程图缩放。下方文字提供同等内容。</p><div class="design-scroll" tabindex="0" role="region" aria-label="${e(c.title)}流程图"><img src="${image}" width="760" height="620" loading="lazy" alt="${e(c.steps.join('；'))}"></div></details></article>`}).join('')}</div></section>`;}

function renderMatchmakingDesignFor(c,e,base) {
  return c.project==='matchmaking-inc'?renderMatchmakingDesign(e,base):'';
}
function renderProjectReference(c,base) {
  if(c.project!=='matchmaking-inc')return '';
  const image=base+'assets/project-design/matchmaking-steam.png';
  return `<figure class="project-reference-image"><a href="${image}" aria-label="查看中国式相亲 Steam 商店截图原图"><img src="${image}" width="1815" height="918" loading="lazy" alt="中国式相亲 Steam 商店页面截图，展示游戏宣传画面、产品介绍及商店信息"></a><figcaption><span>中国式相亲 · Steam 商店截图</span><a href="${image}">查看原图 ↗</a></figcaption></figure>`;
}
export function materialDiagram(c){return `<svg xmlns="http://www.w3.org/2000/svg" width="760" height="620" viewBox="0 0 760 620"><rect width="760" height="620" fill="#eeeaf3"/><style>text{font-family:system-ui,'Microsoft YaHei',sans-serif;fill:#382f48}</style><text x="48" y="62" font-size="25" font-weight="700">${c.title}</text><text x="48" y="94" font-size="16">本站原创脱敏结构图 · 非游戏实机画面</text>${c.steps.map((s,i)=>`<rect x="48" y="${125+i*102}" width="664" height="78" rx="12" fill="${i%2?'#d7ed92':'#f6f3e9'}" stroke="#7e718d"/><text x="74" y="${172+i*102}" font-size="23">${i+1} / ${s}</text>${i<3?`<path d="M380 ${203+i*102}v24" stroke="#382f48" stroke-width="2"/>`:''}`).join('')}<text x="48" y="586" font-size="16">结构表达用于阅读方案，不代表上线状态或个人独立执行范围。</text></svg>`;}
