import {townSupplementCases,renderMuyouCase} from './muyou-evidence.mjs';
// Reviewed historical references, not performance or individual authorship claims.
export const townMaps = [
  {id:'town-navigation',title:'经营界面与功能跳转',file:'navigation.jpg',width:1308,height:1129,sha256:'180bcc3d8376681ea1c3ab6a0142f0ab0afdef837a5c7c2abefcfb51f99f216e',alt:'我的小镇界面关系图：主场景连接未建造商店、商店展示、图鉴、任务、顾客招募、升级与离线收益',question:'如何把经营主场景与建造、补货、顾客和成长入口组织成清晰的操作路径？',points:['以小镇主场景为中心，区分未建造商店的选择与已建造商店的查看。','任务、顾客招募、图鉴、升级和离线收益分别设置界面，保留主场景与功能页之间的跳转关系。','商店、商品、顾客和等级共同承接经营循环；截图中的金额与等级是方案示例，不作为实际业绩。'],output:'界面关系图将场景入口、功能分区和页面目标放在一起，可用于讨论信息架构及跨界面衔接。'},
  {id:'town-onboarding',title:'新手引导与经营循环',file:'onboarding.jpg',width:1492,height:967,sha256:'ce9929c29be6491f2a68d3a8ecb4b065ae9c5735306a4fb9dbde4b52244b8ecf',alt:'我的小镇游戏流程：启动加载、首次CG、未完成引导检查、建造商店、生产商品、招募顾客、加工厂、员工与经营成长循环',question:'首次进入如何逐步建立经营认知，中断后又怎样回到尚未完成的步骤？',points:['从启动和加载进入首次体验判定，将世界介绍、建造商店、商品生产与顾客招募按顺序连接。','图中保留未完成引导的检查和中断后恢复分支，避免首次体验只考虑理想路径。','常规循环由建造、补货、顾客和收益连接升级；更高等级的商店、顾客、任务、宝藏、故事与图鉴成为扩展目标。','退出流程区分确认和取消返回，说明入口之外的结束路径。'],output:'流程图覆盖首次进入、引导步骤、恢复分支、常规经营及退出，可作为策划、程序和测试对齐流程的讨论依据。'},
  {id:'town-task-states',title:'任务与宝藏的交互状态',file:'task-states.jpg',width:1892,height:1076,sha256:'6902792e5e39b648e81f3120f0232e202c94d6131bae00463c85a97f628c6872',alt:'我的小镇任务与宝藏标注线框：待开启、开启中和可领取状态，倒计时、钻石跳过、任务分类、进度、难度及更换重置确认',question:'如何在同一任务界面里，让玩家理解当前状态、可执行动作以及高成本操作的后果？',points:['宝藏区分待开启、开启中和可领取，倒计时、开始及跳过入口对应不同状态。','任务按新手、主线、限时和日常组织，进度条、难度及开始或重试按钮说明目标与反馈。','更换、重置等操作配确认弹窗；返回、资源入口和滚动列表明确页面边界。'],output:'带标注的交互线框描述按钮、状态、反馈和确认分支，支持讨论 UI/UE 交互规则，而非仅展示美术效果。'},
];

export function renderTownCompanyEntry() {
  return `<section class="idiom-company-entry" aria-labelledby="town-company-title"><div><p class="eyebrow">PROJECT EVIDENCE / 我的小镇</p><h2 id="town-company-title">经营循环与交互资料</h2><p>从新手进入、经营成长到任务与宝藏状态，阅读具体的流程图与界面线框。</p></div><a class="text-link" href="../../projects/my-town/#town-design">查看小镇项目资料 ↗</a></section>`;
}

export function renderTownDesign(e,base='../../') {
  return `<section class="matchmaking-design" id="town-design" aria-labelledby="town-design-title"><header><p class="eyebrow">SYSTEM / GAMEPLAY / UI·UE</p><h2 id="town-design-title">我的小镇 · 设计资料</h2><p class="matchmaking-intro">经营小镇的方案资料，将商店建造、商品生产、顾客招募与成长连接起来，并展示新手流程和任务交互。</p></header><p class="matchmaking-boundary">我的任职角色：主策划，2021.05—2022.07。资料来自用户指定的牧游科技项目目录与提供的历史截图；下方为本站整理的阅读摘要，不认定全部方案由个人独立完成，团队美术产出不归为个人美术执行。历史设计图不代表全部功能最终上线，示例数值不是经营成果。</p><nav class="idiom-jumps" aria-label="小镇设计资料">${[...townMaps,...townSupplementCases].map(item=>`<a href="#${item.id}">${e(item.title)} ↓</a>`).join('')}<a href="${base}projects/my-town/design-summary/">设计摘要 ↗</a></nav>${townMaps.map(item=>{
    const image=`${base}assets/project-design/my-town/${item.file}`;
    const attrs=`src="${image}" width="${item.width}" height="${item.height}" loading="lazy" decoding="async" alt="${e(item.alt)}"`;
    return `<article class="matchmaking-map" id="${item.id}" aria-labelledby="${item.id}-title"><h3 id="${item.id}-title">${e(item.title)}</h3><figure><a href="${image}" aria-label="查看${e(item.title)}原图"><img ${attrs}></a><figcaption>我的小镇 · 项目历史设计截图</figcaption></figure><div class="matchmaking-map-notes"><div><h4>设计问题</h4><p>${e(item.question)}</p><h4>图示产出</h4><p>${e(item.output)}</p></div><div><h4>关键方案</h4><ul>${item.points.map(point=>`<li>${e(point)}</li>`).join('')}</ul></div></div><a class="design-original" href="${image}">查看原图（可缩放）<span aria-hidden="true">↗</span></a><details class="matchmaking-inspect"><summary>在页面内阅读${e(item.title)}大图</summary><div class="matchmaking-scroll" tabindex="0" role="region" aria-label="${e(item.title)}大图阅读区域"><img ${attrs}></div></details></article>`;
  }).join('')}${townSupplementCases.map(item=>renderMuyouCase(item,e,base)).join('')}<p class="matchmaking-boundary">项目目录包含系统框架、新手任务、新手引导、游戏流程及美术资源需求等材料。保留三张审核后的设计截图，并补充系统框架、物品数值和项目甘特图摘要，不上传完整内部文档、配置表或源工程；含他人身份及内部任务记录的拼接图不公开。此处不将同公司其他项目的共同职责归为本项目独立成果。</p></section>`;
}
