// Responsibility is grounded in document revision tables; team art stays separate.
export const ttDocuments=[
  {name:'「关卡」关卡玩法优化方案',period:'2022.05—2022.06',evidence:'修订表负责人：吴天昊；创建文档、关卡地图 UE、横向布局与引导流程更新。',target:'tt-levels'},
  {name:'「家装」家装评分系统设计',period:'2021.12—2022.03',evidence:'修订表负责人：吴天昊；评分设计、规则补充与 UE 布局调整。',target:'tt-rating'},
  {name:'「任务系统」主线任务',period:'2022.02—2022.03',evidence:'修订表负责人：吴天昊；创建文档及格式修订。',target:'tt-main'},
  {name:'「任务系统」每日任务',period:'2022.04',evidence:'修订表负责人：吴天昊；创建文档、界面 UE 与详细规则补充。',target:'tt-daily'},
  {name:'新手引导 CB4版',period:'2022.05—2022.06',evidence:'修订表负责人：吴天昊；创建文档、需求概述与图例化说明补充。',target:'tt-onboarding'},
];
export const ttAssets=[
  {file:'level-states.png',width:792,height:354,sha256:'10467a57ac1e02224e575fccfe44cf2cc441ac95e85f266eb347b3db41ef9230',source:'《「关卡」关卡玩法优化方案》图 9 关卡地图参考',alt:'章节地图 UE：已完成、已解锁未完成、未解锁样板间与章节通关领奖，家具点亮和关卡按钮颜色区分状态'},
  {file:'rating-rules.png',width:1496,height:698,sha256:'39dd785c1864d98ab0ac3034424070358f17ab558999d8de51a4d9e89bc102e2',source:'《「家装」家装评分系统设计》家装评分规则导图',alt:'家装评分导图：评分体系、家具风格定义，以及小家主态客态、家装方案和家具详情的评分展示'},
  {file:'main-task-flow.png',width:5250,height:1858,sha256:'a93541e187fdc12e91a88bc8915c598887d605d541af640a863b2eea90bc25d8',source:'《「任务系统」主线任务》任务界面流程参考',alt:'主线任务 UE 流程：小屋任务入口、未达成时前往、达成后领取与通用领奖反馈'},
  {file:'daily-task-flow.png',width:3224,height:1854,sha256:'0fd56b4acb851e74af949eaa785442497f4b9d42c7e60470f0252cff537edcaa',source:'《「任务系统」每日任务》任务与阶段奖励参考',alt:'每日任务 UE：任务入口、阶段礼物进度条、领取和前往按钮、已领取置灰任务与领奖界面'},
  {file:'onboarding-flow.png',width:900,height:506,sha256:'47fefe7394ae0e2f4ccb57244c180bafd6f4270d9440f1555d61655f5cbe8928',source:'《新手引导 CB4版》剧情对话、操作引导与展示面板',alt:'新手引导三种表现：NPC 对话介绍家具、遮罩引导打开家装、家具摆放面板显示移动和确认操作'},
  {file:'wheel-reference.png',width:363,height:645,sha256:'e5372cfea2ec07df412c359c0ddb8d4897db8fd66b7e1d812f712944c0948224',source:'《「关卡」关卡玩法优化方案》图 1，原图未修改的转盘参考',alt:'转盘已有界面参考：资源条、守护和捣乱等事件、倍率、长按自动按钮及小屋装修入口，昵称和资源为示例'},
  {file:'shield-guide.png',width:652,height:1162,sha256:'d899d06c1bca2af5999b69819d33a10fba53d12686fb5c3570609b39c2600db6',source:'《新手引导 CB4版》美术需求中的护盾教学参考',alt:'护盾图例教学草图：盾牌保护房间的效果，文字说明防止捣乱，并设置知道了按钮'},
];
const imagePath=(base,file)=>`${base}assets/project-design/party-planet/${file}`;
function image(file,e,base){const a=ttAssets.find(a=>a.file===file);return `<img src="${imagePath(base,file)}" width="${a.width}" height="${a.height}" loading="lazy" decoding="async" alt="${e(a.alt)}">`;}
function evidence({id,title,file,question,points,output},e,base){const a=ttAssets.find(a=>a.file===file),path=imagePath(base,file);return `<article class="matchmaking-map" id="${id}" aria-labelledby="${id}-title"><h3 id="${id}-title">${e(title)}</h3><figure><a href="${path}" aria-label="查看${e(title)}原图">${image(file,e,base)}</a><figcaption>${e(a.source)} · 原始嵌入参考</figcaption></figure><div class="matchmaking-map-notes"><div><h4>设计问题</h4><p>${e(question)}</p><h4>文档产出</h4><p>${e(output)}</p></div><div><h4>关键方案</h4><ul>${points.map(p=>`<li>${e(p)}</li>`).join('')}</ul></div></div><a class="design-original" href="${path}">查看原图（可缩放）<span aria-hidden="true">↗</span></a><details class="matchmaking-inspect"><summary>在页面内阅读${e(title)}大图</summary><div class="matchmaking-scroll" tabindex="0" role="region" aria-label="${e(title)}大图阅读区域">${image(file,e,base)}</div></details></article>`;}
export function renderTTDesign(e,base='../../'){
 return `<section class="matchmaking-design" id="tt-design" aria-labelledby="tt-design-title"><header><p class="eyebrow">GAMEPLAY / SYSTEM / UI·UE · TT 趣丸</p><h2 id="tt-design-title">关卡、任务与新手体验</h2><p class="matchmaking-intro">以转盘、家具收集和小屋装扮连接成长，用主线、每日任务和分阶段引导建立游玩目标。我的任职角色：高级系统策划，2021.12—2022.07。</p></header><p class="matchmaking-boundary">以下五份文档的修订表明确记录负责人“吴天昊”，据此说明文档创建、规则和交互修订贡献，不认定全部玩法、程序与美术均由个人独立完成；美术执行由团队相关岗位承担。资料使用“派对总动员”等阶段性名称，按用户指定的 TT 项目资料接入履历中的《派对星球》，不据此宣称正式更名。历史方案、数据目标及示例数值不作为上线证明或实际业绩。</p><nav class="idiom-jumps" aria-label="TT 项目设计资料">${ttDocuments.map(d=>`<a href="#${d.target}">${e(d.name.replace(/「[^」]+」/u,''))} ↓</a>`).join('')}<a href="#tt-art">界面与教学参考 ↓</a><a href="${base}projects/party-planet/design-summary/">设计摘要 ↗</a></nav><section class="idiom-chapter" aria-labelledby="tt-documents-title"><h3 id="tt-documents-title">有修订记录支持的策划资料</h3><div class="beta-document-list">${ttDocuments.map(d=>`<div><h4><a href="#${d.target}">${e(d.name)}</a></h4><p>${e(d.evidence)}</p><p class="matchmaking-boundary">修订记录 ${e(d.period)}</p></div>`).join('')}</div></section>
 ${evidence({id:'tt-levels',title:'章节地图与家具收集状态',file:'level-states.png',question:'怎样让玩家从关卡编号理解章节成长、家具解锁以及下一步可做什么？',points:['以样板间组织章节，将家具点亮程度与关卡进度结合，区分已完成、已解锁未完成及未解锁三类状态。','地图由纵向调整为横向浏览，支持拖动与左右按钮；默认定位到当前章节，并显示奖励详情。','关卡按钮区分已完成、当前、未完成和选中状态；样板间解锁后可跳到小屋家装并应用家具预设。','通关后按领奖、分享、章节解锁与新关卡点亮顺序反馈；首次引导屏蔽重复章节领奖和全屏刷新表现。'],output:'修订记录包含地图 UE、横向布局与引导流程更新。文档同时说明转盘长按反馈、倍率提示、资源条及界面切换；这里只展示状态与交互，具体配置和概率不公开。'},e,base)}
 ${evidence({id:'tt-rating',title:'家装评分与主客态展示',file:'rating-rules.png',question:'如何把家具收集与布置变成可理解的成长目标，同时保持编辑和拜访中的数据一致？',points:['以家具风格属性形成华丽度总分；常规家装看总分，评分玩法按所要求的风格显示对应数值。','摆放或撤回家具、切换方案时即时更新编辑分数，并用增加或减少的反馈表达变化。','主态保存方案后计算并提交评分，刷新展示；客态拜访时读取对方评分和家具状态，不要求实时追踪所有变化。','评分详情、家具详情与方案窗口承担不同信息层级，避免只给一个总分却无法解释来源。'],output:'文档覆盖规则导图、评分展示、编辑反馈、主客态同步及界面需求，修订表记录了规则与 UE 布局调整；不公开内部评分档位配置。'},e,base)}
 ${evidence({id:'tt-main',title:'主线任务的判定与目标引导',file:'main-task-flow.png',question:'怎样把家装、关卡和社交行为串成线性目标，并避免计数起点与任务状态含糊？',points:['任务判断区分行为事件与收集进度；收集任务再区分注册以来累计、任务开始后累计两个计数起点。','完成前一任务解锁后续任务；未达成显示前往，达成后显示领取，并以进度提示和红点承接状态变化。','任务面板优先定位到有奖励可领取的页签；各页签提示全部解除后才清除主入口红点。','任务条件按类型和条件组织，并记录入口、目标完成、领奖与跳转事件，便于检查引导路径。'],output:'修订表记录本人创建与修订任务文档。任务体系用家装、关卡等功能作为目标对象，不表示这些外围系统全部由本人独立设计。'},e,base)}
 ${evidence({id:'tt-daily',title:'每日任务、排序与阶段奖励',file:'daily-task-flow.png',question:'每天的短目标如何与长期系统学习衔接，并让任务与礼包的领取状态保持清晰？',points:['任务完成获得资源与任务点数，点数累计到阶段礼物；服务器固定时间刷新，初期任务可按教学需要固定安排。','区分前往、领取和已领取状态；排序优先可领取，其次未完成，最后已完成，领完后置灰下沉。','阶段礼物区分待领取与已领取；奖励气泡随位置调整指向，支持查看下一级奖励。','任务跳转读取目标配置，进度和按钮随行为更新；入口、领奖和阶段礼物分别记录事件。'],output:'修订表明确记录本人创建文档、修改界面 UE 并补充详细规则；任务数量、奖励数值和达成率目标不当作线上数据或个人业绩。'},e,base)}
 ${evidence({id:'tt-onboarding',title:'分阶段引导与中断处理',file:'onboarding-flow.png',question:'第一次进入怎样让玩家理解核心价值，并避免把所有系统操作一次性堆给新用户？',points:['先介绍角色、小屋、转盘与家具成长，再分阶段教学家装换装、拜访互动、小屋升级和派对参与。','区分剧情对话、遮罩操作、功能图例及弱引导，图例有行动按钮时跳到对应功能，没有按钮时可关闭。','文档并列讨论中断后跳过上一步或恢复中断界面的两种方案，不将其表述为已确定的唯一实现。','逐步定义点击、触达完成、相邻步骤停留时长、加载与启动事件，用于定位理解或流程中的流失点。'],output:'CB4 记录了本人创建、需求概述与图例说明补充；文档也注明了其他岗位负责的开发事项，本站不扩大个人责任或展示未验证的引导通过率。'},e,base)}
 <section class="idiom-chapter" id="tt-art" aria-labelledby="tt-art-title"><p class="eyebrow">INTERFACE REFERENCES / 团队协作资料</p><h3 id="tt-art-title">从交互规则到界面表现</h3><p>左图是关卡优化案明确标为“原图未修改”的转盘已有界面，右图是 CB4 美术需求中的护盾教学参考。图示用于说明信息层级、按钮状态和功能解释，不作为本人绘制作品或最终上线截图。</p><div class="idiom-assets-grid">${ttAssets.slice(5).map(a=>`<figure class="idiom-reference"><a href="${imagePath(base,a.file)}" aria-label="查看${e(a.alt)}原图">${image(a.file,e,base)}</a><figcaption><span>${e(a.source)}</span><a href="${imagePath(base,a.file)}">查看原图 ↗</a></figcaption></figure>`).join('')}</div><div class="matchmaking-map-notes"><div><h4>交互交付</h4><p>转盘界面需要区分点击、长按自动、资源不足等按钮状态，关卡与小屋入口保持明确；教学图将护盾作用用房间和屏障说明，再通过确认按钮返回游玩。</p></div><div><h4>公开范围</h4><p>图片中昵称、资源、等级和奖励按历史设计示例理解，不作为真实玩家数据。完整内部文档、产出表、经济配置与其他负责人方案不公开，也不归为个人独立成果。</p></div></div></section></section>`;
}
